
service: mememaker

provider:
  name: aws
  runtime: nodejs12.x

package:
  individually: true
  excludeDevDependencies: true 

exclude:
  - ./dependencies.zip
  - ./dependencies/
  - ./mock/
  - ./node_modules


functions:
  mememaker:
    handler: app/handler.mememaker
    layers:
      - {Ref: GmLibraryLambdaLayer}
      - {Ref: NodeModulesLambdaLayer}
    events:
      - http:
          method: get
          path: mememaker
          cors: true

layers:
  GmLibrary:
    package:
      artifact: dependencies.zip
  NodeModules:
    path: layer
    compatibleRuntimes:
      - nodejs12.x


